# Generated by Django 5.0.1 on 2024-02-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='question_image',
            new_name='youtube_image',
        ),
        migrations.AddField(
            model_name='qna',
            name='youtube_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
