# Generated by Django 5.0.1 on 2024-02-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_question_image_qna_youtube_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='youtube_image',
            new_name='question_image',
        ),
    ]
