# Generated by Django 5.0.1 on 2024-03-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_youtube_image_qna_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='arabic_comment',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='chinese_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='english_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='french_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='german_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hindi_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='japanese_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='portuguese_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='russian_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='spanish_comment',
        ),
    ]
