# Generated by Django 5.0.1 on 2024-03-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_comment_comment_arabic_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='showhide',
        ),
    ]
