# Generated by Django 5.0.1 on 2024-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_comment_showhide'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='showhide',
            field=models.CharField(choices=[('hide', 'hide'), ('show', 'show')], default='hide', max_length=20),
        ),
    ]
