# Generated by Django 5.0.1 on 2024-03-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment_showhide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='showhide',
        ),
    ]
